	<script type="text/javascript" src="<?=$site_host?>/js/vendor/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/slick.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/swiper.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/gsap.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/ScrollToPlugin.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/splitting.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/jquery.waypoints.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/jquery.magnific-popup.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/plugin/spotlight.min.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/functions.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/nav.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/layer_popup.js"></script>
	<script type="text/javascript" src="<?=$site_host?>/js/common.js"></script>